spring.datasource.url=jdbc:postgresql://localhost:5433/telegram
spring.datasource.username=student
spring.datasource.password=10198
spring.jpa.hibernate.ddl-auto=create
telegram.bot.token=7777386011:AAFWAxwN4EyLTbu6hAeZoQeGDJWo5XgKaEY



spring.liquibase.change-log=classpath:liquibase/changelog-master.yml